### PR TITLE
Add conda activation/deactivation script for PowerShell and Bash on Windows

### PR DESCRIPTION
**Pull request by dan9401**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Local build seems to work successfully in PowerShell and Bash, please take a look and see if additional changes are needed.

### CODE REVIEW

**Comment by dan9401** [comment]
@conda-forge-admin, please rerender

**Comment by mfisher87** [comment]
Thanks for this! This looks good to me, but I don't have the bandwidth to set up a test environment at the moment. How have you tested this change?

I feel like we should probably extract the activation scripts into files and then copy them into place in the build scripts, as we're duplicating the bash script's contents in `build.sh` and `bld.bat` now. I don't think that needs to be part of this PR unless you feel like it! :)

**Comment by dan9401** [comment]
I installed the build tarball by `conda-build` in a new environment and tested the installation in PowerShell and bash.

I can take a look at separating the scripts, would you recommend I put the separated scripts directly in `recipe/`?

**Comment by mfisher87** [comment]
I think we can save separating the scripts for another PR if you'd prefer. If you're up for it though, I think it makes a lot of sense since this PR introduces the duplication of the bash script contents. What do you think about `recipe/activate/`?

**Comment by dan9401** [comment]
Got it, I think it still make sense for the separation to happen in the same PR.

I'll take a look after work today, unless I run into unexpected problems I think I'll try to update here.

**Comment by mfisher87** [comment]
:bow: Thanks for your help!

**Comment by dan9401** [comment]
@mfisher87 , I took a closer look, and with my limited scripting and `conda-build` knowledge, I wonder if benefit of the separation outweight the complexity introduced with the following observations:

1. The paths are different on Windows vs that of UNIX. As an example, all the `$PREFIX/bin` on UNIX are `%PREFIX%/Library/bin` on Windows.
2. The extensions are different. Such as `.exe` needed for Windows, and `.so` vs `.dll`.
3. If we want to leverage the environment variables such as `DENO_DOM_PLUGIN` from the build environment, the activation script need to be evaluated in the build script, and variables have different syntaxex in `.bat` and `.sh`. Since all the `$QUARTO_` vars are locations in `$CONDA_PREFIX`, we can technically reconstruct all the paths in the activation script, but that's an additional item to maintain.

**Comment by mfisher87** [comment]
Good point. This is how GDAL handles that in their shared bash script: https://github.com/conda-forge/gdal-feedstock/blob/d15791acbda55124802457402eaa4e303f36c889/recipe/scripts/activate.sh

I do question whether it's worth it to maintain that. Thanks for your help thinking this through! Perhaps it still makes sense to extract the activation scripts instead of inlining them, while still keeping the Windows and Linux bash scripts as separate source files.

Let's get this PR merged first, though, instead of taking it off track. Thank you again for your work!

**Review by mfisher87 — APPROVED** [review]

**Comment by mfisher87** [comment]
Thanks so much @dan9401 !!

**Pull request merged**
