### PR TITLE
1.5.55-1: Pin pandoc more strictly and restore quarto-preview.js

### LINKED ISSUE #53: `quarto-preview.js` missing in 1.4.557, 1.5.55
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
$ quarto preview
<...>
WARNING: No such file or directory (os error 2): readfile '/path/to/miniforge3/envs/envname/share/quarto/preview/quarto-preview.js'
$ ls -1 /path/to/miniforge3/envs/envname/share/quarto/preview/
jats/
quarto-preview.html
```

The .js file is present in 1.4.550; it was poor testing on my part for #50 I think. I was sure I'd tested preview :confused: 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### LINKED ISSUE #58: Pandoc installed and used is higher than the one supported by Quarto
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I've described at https://github.com/quarto-dev/quarto-cli/issues/10682 an issue I've been having with the `conda-forge` version of `quarto`. 

## Issue
With using quarto render file.qmd --to pdf on
```qmd
# Test

![](file.png)
```
when `file.png` exists in the directory, LaTeX compilation fails with
```
ERROR: 
compilation failed- error
Undefined control sequence.
l.227 \pandocbounded
                    {\includegraphics[keepaspectratio]{
```

It looks to me like the [\pandocbounded](https://github.com/jgm/pandoc/releases/tag/3.2.1) function added to pandoc on 3.2.1 is not defined in some step of the rendering.

Error is given on
```
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.1: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /.../micromamba/envs/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5 (Conda)
      Path: /.../micromamba/envs/quarto/bin/python
      Jupyter: 5.7.2
      Kernels: python3, julia-1.10

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
but with downgrading via `mamba install "pandoc<3.2" quarto` everything is ok:
```
Quarto 1.4.557
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.12: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.557
      Path: /.../micromamba/envs/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5 (Conda)
      Path: /.../micromamba/envs/quarto/bin/python
      Jupyter: 5.7.2
      Kernels: python3, julia-1.10

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

## Extra

The developers over there also highlighted that the feedstock should be following dependencies outlined in [here](https://github.com/quarto-dev/quarto-cli/blob/main/configuration) though perhaps that is a separate issue.

### Installed packages

```shell
_libgcc_mutex                  0.1             conda_forge         conda-forge
  _openmp_mutex                  4.5             2_gnu               conda-forge
  anyio                          4.4.0           pyhd8ed1ab_0        conda-forge
  argon2-cffi                    23.1.0          pyhd8ed1ab_0        conda-forge
  argon2-cffi-bindings           21.2.0          py312h98912ed_4     conda-forge
  arrow                          1.3.0           pyhd8ed1ab_0        conda-forge
  asttokens                      2.4.1           pyhd8ed1ab_0        conda-forge
  async-lru                      2.0.4           pyhd8ed1ab_0        conda-forge
  attrs                          24.2.0          pyh71513ae_0        conda-forge
  babel                          2.14.0          pyhd8ed1ab_0        conda-forge
  beautifulsoup4                 4.12.3          pyha770c72_0        conda-forge
  bleach                         6.1.0           pyhd8ed1ab_0        conda-forge
  brotli-python                  1.1.0           py312h30efb56_1     conda-forge
  bzip2                          1.0.8           h4bc722e_7          conda-forge
  ca-certificates                2024.7.4        hbcca054_0          conda-forge
  cached-property                1.5.2           hd8ed1ab_1          conda-forge
  cached_property                1.5.2           pyha770c72_1        conda-forge
  certifi                        2024.7.4        pyhd8ed1ab_0        conda-forge
  cffi                           1.17.0          py312h1671c18_0     conda-forge
  charset-normalizer             3.3.2           pyhd8ed1ab_0        conda-forge
  click                          8.1.7           unix_pyh707e725_0   conda-forge
  comm                           0.2.2           pyhd8ed1ab_0        conda-forge
  dart-sass                      1.58.3          ha770c72_1          conda-forge
  debugpy                        1.8.5           py312hca68cad_0     conda-forge
  decorator                      5.1.1           pyhd8ed1ab_0        conda-forge
  defusedxml                     0.7.1           pyhd8ed1ab_0        conda-forge
  deno                           1.41.0          hfc7925d_0          conda-forge
  deno-dom                       0.1.35          hd9586b0_1          conda-forge
  entrypoints                    0.4             pyhd8ed1ab_0        conda-forge
  esbuild                        0.19.2          ha770c72_0          conda-forge
  exceptiongroup                 1.2.2           pyhd8ed1ab_0        conda-forge
  executing                      2.0.1           pyhd8ed1ab_0        conda-forge
  fqdn                           1.5.1           pyhd8ed1ab_0        conda-forge
  greenlet                       3.0.3           py312h30efb56_0     conda-forge
  h11                            0.14.0          pyhd8ed1ab_0        conda-forge
  h2                             4.1.0           pyhd8ed1ab_0        conda-forge
  hpack                          4.0.0           pyh9f0ad1d_0        conda-forge
  httpcore                       1.0.5           pyhd8ed1ab_0        conda-forge
  httpx                          0.27.0          pyhd8ed1ab_0        conda-forge
  hyperframe                     6.0.1           pyhd8ed1ab_0        conda-forge
  idna                           3.7             pyhd8ed1ab_0        conda-forge
  importlib-metadata             8.2.0           pyha770c72_0        conda-forge
  importlib_metadata             8.2.0           hd8ed1ab_0          conda-forge
  importlib_resources            6.4.0           pyhd8ed1ab_0        conda-forge
  ipykernel                      6.29.5          pyh3099207_0        conda-forge
  ipython                        8.26.0          pyh707e725_0        conda-forge
  ipywidgets                     8.1.3           pyhd8ed1ab_0        conda-forge
  isoduration                    20.11.0         pyhd8ed1ab_0        conda-forge
  jedi                           0.19.1          pyhd8ed1ab_0        conda-forge
  jinja2                         3.1.4           pyhd8ed1ab_0        conda-forge
  json5                          0.9.25          pyhd8ed1ab_0        conda-forge
  jsonpointer                    3.0.0           py312h7900ff3_0     conda-forge
  jsonschema                     4.23.0          pyhd8ed1ab_0        conda-forge
  jsonschema-specifications      2023.12.1       pyhd8ed1ab_0        conda-forge
  jsonschema-with-format-nongpl  4.23.0          hd8ed1ab_0          conda-forge
  jupyter                        1.0.0           pyhd8ed1ab_10       conda-forge
  jupyter-cache                  1.0.0           pyhd8ed1ab_0        conda-forge
  jupyter-lsp                    2.2.5           pyhd8ed1ab_0        conda-forge
  jupyter_client                 8.6.2           pyhd8ed1ab_0        conda-forge
  jupyter_console                6.6.3           pyhd8ed1ab_0        conda-forge
  jupyter_core                   5.7.2           py312h7900ff3_0     conda-forge
  jupyter_events                 0.10.0          pyhd8ed1ab_0        conda-forge
  jupyter_server                 2.14.2          pyhd8ed1ab_0        conda-forge
  jupyter_server_terminals       0.5.3           pyhd8ed1ab_0        conda-forge
  jupyterlab                     4.2.4           pyhd8ed1ab_0        conda-forge
  jupyterlab_pygments            0.3.0           pyhd8ed1ab_1        conda-forge
  jupyterlab_server              2.27.3          pyhd8ed1ab_0        conda-forge
  jupyterlab_widgets             3.0.11          pyhd8ed1ab_0        conda-forge
  keyutils                       1.6.1           h166bdaf_0          conda-forge
  krb5                           1.21.3          h659f571_0          conda-forge
  ld_impl_linux-64               2.40            hf3520f5_7          conda-forge
  libedit                        3.1.20191231    he28a2e2_2          conda-forge
  libexpat                       2.6.2           h59595ed_0          conda-forge
  libffi                         3.4.2           h7f98852_5          conda-forge
  libgcc-ng                      14.1.0          h77fa898_0          conda-forge
  libgomp                        14.1.0          h77fa898_0          conda-forge
  libnsl                         2.0.1           hd590300_0          conda-forge
  libsodium                      1.0.18          h36c2ea0_1          conda-forge
  libsqlite                      3.46.0          hde9e2c9_0          conda-forge
  libstdcxx-ng                   14.1.0          hc0a3c3a_0          conda-forge
  libuuid                        2.38.1          h0b41bf4_0          conda-forge
  libxcrypt                      4.4.36          hd590300_1          conda-forge
  libzlib                        1.3.1           h4ab18f5_1          conda-forge
  markupsafe                     2.1.5           py312h98912ed_0     conda-forge
  matplotlib-inline              0.1.7           pyhd8ed1ab_0        conda-forge
  mistune                        3.0.2           pyhd8ed1ab_0        conda-forge
  nbclient                       0.10.0          pyhd8ed1ab_0        conda-forge
  nbconvert                      7.16.4          hd8ed1ab_1          conda-forge
  nbconvert-core                 7.16.4          pyhd8ed1ab_1        conda-forge
  nbconvert-pandoc               7.16.4          hd8ed1ab_1          conda-forge
  nbformat                       5.10.4          pyhd8ed1ab_0        conda-forge
  ncurses                        6.5             h59595ed_0          conda-forge
  nest-asyncio                   1.6.0           pyhd8ed1ab_0        conda-forge
  notebook                       7.2.1           pyhd8ed1ab_0        conda-forge
  notebook-shim                  0.2.4           pyhd8ed1ab_0        conda-forge
  openssl                        3.3.1           h4bc722e_2          conda-forge
  overrides                      7.7.0           pyhd8ed1ab_0        conda-forge
  packaging                      24.1            pyhd8ed1ab_0        conda-forge
  pandoc                         3.2.1           ha770c72_0          conda-forge
  pandocfilters                  1.5.0           pyhd8ed1ab_0        conda-forge
  parso                          0.8.4           pyhd8ed1ab_0        conda-forge
  pexpect                        4.9.0           pyhd8ed1ab_0        conda-forge
  pickleshare                    0.7.5           py_1003             conda-forge
  pip                            24.2            pyhd8ed1ab_0        conda-forge
  pkgutil-resolve-name           1.3.10          pyhd8ed1ab_1        conda-forge
  platformdirs                   4.2.2           pyhd8ed1ab_0        conda-forge
  prometheus_client              0.20.0          pyhd8ed1ab_0        conda-forge
  prompt-toolkit                 3.0.47          pyha770c72_0        conda-forge
  prompt_toolkit                 3.0.47          hd8ed1ab_0          conda-forge
  psutil                         6.0.0           py312h9a8786e_0     conda-forge
  ptyprocess                     0.7.0           pyhd3deb0d_0        conda-forge
  pure_eval                      0.2.3           pyhd8ed1ab_0        conda-forge
  pycparser                      2.22            pyhd8ed1ab_0        conda-forge
  pygments                       2.18.0          pyhd8ed1ab_0        conda-forge
  pysocks                        1.7.1           pyha2e5f31_6        conda-forge
  python                         3.12.5          h2ad013b_0_cpython  conda-forge
  python-dateutil                2.9.0           pyhd8ed1ab_0        conda-forge
  python-fastjsonschema          2.20.0          pyhd8ed1ab_0        conda-forge
  python-json-logger             2.0.7           pyhd8ed1ab_0        conda-forge
  python_abi                     3.12            4_cp312             conda-forge
  pytz                           2024.1          pyhd8ed1ab_0        conda-forge
  pyyaml                         6.0.2           py312h41a817b_0     conda-forge
  pyzmq                          26.1.0          py312h7ab5c7e_0     conda-forge
  qtconsole-base                 5.5.2           pyha770c72_0        conda-forge
  qtpy                           2.4.1           pyhd8ed1ab_0        conda-forge
  quarto                         1.5.55          ha770c72_0          conda-forge
  readline                       8.2             h8228510_1          conda-forge
  referencing                    0.35.1          pyhd8ed1ab_0        conda-forge
  requests                       2.32.3          pyhd8ed1ab_0        conda-forge
  rfc3339-validator              0.1.4           pyhd8ed1ab_0        conda-forge
  rfc3986-validator              0.1.1           pyh9f0ad1d_0        conda-forge
  rpds-py                        0.20.0          py312hf008fa9_0     conda-forge
  send2trash                     1.8.3           pyh0d859eb_0        conda-forge
  setuptools                     72.1.0          pyhd8ed1ab_0        conda-forge
  six                            1.16.0          pyh6c4a22f_0        conda-forge
  sniffio                        1.3.1           pyhd8ed1ab_0        conda-forge
  soupsieve                      2.5             pyhd8ed1ab_1        conda-forge
  sqlalchemy                     2.0.32          py312h41a817b_0     conda-forge
  stack_data                     0.6.2           pyhd8ed1ab_0        conda-forge
  tabulate                       0.9.0           pyhd8ed1ab_1        conda-forge
  terminado                      0.18.1          pyh0d859eb_0        conda-forge
  tinycss2                       1.3.0           pyhd8ed1ab_0        conda-forge
  tk                             8.6.13          noxft_h4845f30_101  conda-forge
  tomli                          2.0.1           pyhd8ed1ab_0        conda-forge
  tornado                        6.4.1           py312h9a8786e_0     conda-forge
  traitlets                      5.14.3          pyhd8ed1ab_0        conda-forge
  types-python-dateutil          2.9.0.20240316  pyhd8ed1ab_0        conda-forge
  typing-extensions              4.12.2          hd8ed1ab_0          conda-forge
  typing_extensions              4.12.2          pyha770c72_0        conda-forge
  typing_utils                   0.1.0           pyhd8ed1ab_0        conda-forge
  typst                          0.11.0          he8a937b_0          conda-forge
  tzdata                         2024a           h0c530f3_0          conda-forge
  uri-template                   1.3.0           pyhd8ed1ab_0        conda-forge
  urllib3                        2.2.2           pyhd8ed1ab_1        conda-forge
  wcwidth                        0.2.13          pyhd8ed1ab_0        conda-forge
  webcolors                      24.6.0          pyhd8ed1ab_0        conda-forge
  webencodings                   0.5.1           pyhd8ed1ab_2        conda-forge
  websocket-client               1.8.0           pyhd8ed1ab_0        conda-forge
  wheel                          0.44.0          pyhd8ed1ab_0        conda-forge
  widgetsnbextension             4.0.11          pyhd8ed1ab_0        conda-forge
  xz                             5.2.6           h166bdaf_0          conda-forge
  yaml                           0.2.5           h7f98852_2          conda-forge
  zeromq                         4.3.5           h75354e8_4          conda-forge
  zipp                           3.19.2          pyhd8ed1ab_0        conda-forge
  zstandard                      0.23.0          py312h3483029_0     conda-forge
  zstd                           1.5.6           ha6fb4c9_0          conda-forge
```

### Environment info

```shell
libmamba version : 1.5.8
     micromamba version : 1.5.8
           curl version : libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /.../micromamba/envs
          package cache : /.../micromamba/pkgs
                          /.../.mamba/pkgs
            environment : quarto (active)
           env location : /.../micromamba/envs/quarto
      user config files : /.../.mambarc
 populated config files : /.../.condarc
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v4
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /.../micromamba
               platform : linux-64
```

### PR DESCRIPTION
**Pull request by mfisher87**
Closes #58 
Closes #53 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfisher87** [comment]
@conda-forge-admin, please rerender

**Comment by mfisher87** [comment]
Can we also fix the problem with `quarto-preview.js` not getting packaged as part of this release? I don't have any ideas yet why this stopped working. @cderv any idea on your end?

**Comment by mfisher87** [comment]
Restoring the patch we used to use to force it to be built fixed the problem. I thought this was no longer needed due to upstream changes, and didn't test thoroughly enough it seems.

**Comment by mfisher87** [comment]
This did not result in the pin I expected. The repodata shows:

```
    "pandoc 3.2.*",
    "typst 0.11.0.*"
```

**Comment by mfisher87** [comment]
Latest commit fixes it:

```
    "pandoc 3.2",
    "typst 0.11.0"
```

**Comment by cderv** [comment]
This is really awesome ! Thank you ! 

> Restoring the patch we used to use to force it to be built fixed the problem (https://github.com/conda-forge/quarto-feedstock/commit/05329702a60f311a5c90bc7a8cbaceea25b61729). I thought this was no longer needed due to upstream changes, and I didn't test thoroughly enough it seems.

Oh so this was it. I thought also this was handled now. 🤔 
I'll try to understand why it did not happened as expected.

**Pull request merged**
