### PR TITLE
Quarto 1.4 has a new `make-installer-dir` for quarto-bld

### LINKED ISSUE #27: Contribute "external installer" patch to upstream
I thought this had already been done, or a TODO maybe created, but I'm having trouble finding it.

This patch:

https://github.com/MattF-NSIDC/quarto-feedstock/blob/95a3bd9494f63a8d1eafd18395be9437e31943d3/recipe/0001-add-external-installer-command-for-packagers-like-co.patch

Should be incorporated upstream, IMO.

Upstream issue: https://github.com/quarto-dev/quarto-cli/issues/6575

Once this is completed :point_up: we need to remove our patch and leverage the new installer/preparer.

FYI: @cderv

### PR DESCRIPTION
**Pull request by cderv**
This means the patch is no more required

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This closes #27

I haven't check all the boxes above because not sure what to modify or tests. I'll try it if you advise. I am opening this PR to remember to do that for Quarto 1.4 release.

### CODE REVIEW

**Comment by mfisher87** [comment]
Hey @cderv apologies for being unresponsive lately, your patience is appreciated :heart: 

I still may not get to this for another week or two. Just wanted to make sure you know I've seen this and will get to it at some point soon :) I've got these sitting in my notifications so I don't forget.

**Comment by mfisher87** [comment]
I think what I want to do is set up a Quarto 1.4 pre-release branch where we can test this in advance of the release. I haven't done it before, so hopefully I won't get stuck :)

**Comment by cderv** [comment]
No worries ! 

Quarto v1.4 is soon to be release, so we can definitely do some prepare work first ! 

Is there a pre-release or release canditate state for conda feedstock ?

**Comment by mfisher87** [comment]
Yes, that's documented here: https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

I've used pre-release builds before (and I think I may have contributed to that doc page), but have never set up a pre-release build as a feedstock maintainer before.

**Comment by mdekstrand** [comment]
I was looking into this a bit to see what's needed to get Quarto up to 1.4, and it looks like it's blocking on a Pandoc update, unless the pandoc dependency specification can be relaxed.

**Comment by mfisher87** [comment]
Thanks for looking in to this @mdekstrand ! I hope to have more time to help out over the weekend. I don't think I've worked on the Pandoc feedstock before.

**Comment by SaravananSathyanandhaQC** [comment]
> I was looking into this a bit to see what's needed to get Quarto up to 1.4, and it looks like it's blocking on a Pandoc update, unless the pandoc dependency specification can be relaxed.

If you mean getting the pandoc feedstock updated then it's nearly ready - https://github.com/conda-forge/pandoc-feedstock/pull/139

**Comment by mfisher87** [comment]
Amazing! Thank you :) I hope to take a stab at releasing 1.4 on Conda Forge this weekend, and that certainly makes my life easier :)

**Comment by mfisher87** [comment]
Resolved in #36 ; thank you @cderv and @SaravananSathyanandhaQC !

**Pull request closed without merging**
